format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$container\
$docker_context\
$package\
$elixir\
$golang\
$java\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$swift\
$terraform\
$aws\
$azure\
$cmd_duration\
$jobs\
$time\
$status\
$line_break\
$character\
"""

[username]
style_user = "green bold"
show_always = true
format = "[$user]($style) "

[time]
disabled = false
time_format = "%a %d %h %Y %T"

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "

[python]
format = 'via [$symbol($version)( \($virtualenv\))]($style) '

[nodejs]
format = "via [$symbol($version)]($style) "

[hostname]
ssh_only = false
format = "@ [$hostname]($style) "
