(("default" . ((user-emacs-directory . "~/.config/doom-emacs")
               (env . (("DOOMDIR" . "~/.config/doom")))))
 ("doom" . ((user-emacs-directory . "~/.config/doom-emacs")
            (env . (("DOOMDIR" . "~/.config/doom")))))
 ("custom" . ((user-emacs-directory . "~/.config/custom-emacs")))
 ("plain" . ((user-emacs-directory . "~/.config/plainmacs")))
 ("vanilla" . ((user-emacs-directory . "~/.config/vanillamacs")))
 ("space" . ((user-emacs-directory . "~/.config/spacemacs"))))
